version: "3"
services:
  bot:
    image: bot
    build: .
    ports:
    - "18080:80"
    env_file:
    - .env
    volumes:
    - github-notifications-store:/store

volumes:
- github-notifications-store
